export const FETCH_PRODUCTS = `FETCH_PRODUCTS`;

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_TO_CART = 'UPDATE_PRODUCT_TO_CART';
export const CLEAR_PRODUCT_TO_CART = 'CLEAR_PRODUCT_TO_CART';

